### ISSUE TITLE
use PyTest for tests?

### ISSUE THREAD

**Issue by rc** [sfepy/sfepy#363]
It looks like NumPy and SciPy are going to use http://doc.pytest.org/ for tests. Is it worth changing our testing framework?

**Comment by heczis** [comment]
I am for changing the testing framework, since it would reduce the codebase and make use of a standard tool for testing (making it easier for people to transfer knowledge from other projects).
Personally, I would prefer `unittest`, since it is part of the standard library - this way we would not add a dependency.

**Comment by rc** [comment]
For clarification: I created this issue based on the scipy mailing list discussion and [GSoC topic proposals](https://github.com/scipy/scipy/wiki/GSoC-2017-project-ideas). SciPy is already our dependency, so if they switch... This is not an urgent topic, but, of course, PRs (also proof-of-concept kind) are welcome! :)

**Comment by deeptavker** [comment]
Hey! I'm new to open source and have been working on test driven development for a while. I recently did some work with pytest and I know the basic unittest.TestCase subclassing, assert statements and fixtures and CI. I'd like to take this up in case it is decided to shift to pytest.

**Comment by rc** [comment]
@deeptavker thanks for the offer, we will ping you in case we decide going this way.
