### ISSUE TITLE
Two Material Modal Analysis

### ISSUE THREAD

**Issue by lbeardslee1963** [sfepy/sfepy#732]
Hi sfepy,

I have been working on putting together a modal analysis application and it has worked really great so far with single materials. I am now wanting to extend it to problems of multimaterial domains. I have been able to make it work on a two material domain so far but when comparing to a commercial software my answers and mode shapes are quite different. I get some of the same mode shapes but they are in different orders and in some cases modes are missing from one or the other. I am wondering if this is do to a difference in the domain boundaries? I am doing an apples to apples comparison between the two, and using two simple cube shapes, do you think that the interface between the two meshes is being defined differently? And that this would ultimately affect the mode shapes? I am also wondering if it would be possible to include a thin elastic region at the mesh boundaries. I realize this may not be enough information to answer the issue, but please let me know what else would help you address the issue and I will try to provide that information.

**Comment by lbeardslee1963** [comment]
I will have to run this again in the commercial software to double check. The other thing I am going to try is comparing the results from sfepy with real data. I have access to a 3D scanning laser doppler vibrometer, so I am going to take a look at a composite build up and see which software more accurately matches the real data. I will let you know how this goes.

**Comment by rc** [comment]
Thanks, it would be great to have actual real data.

**Comment by lbeardslee** [comment]
Alright, I was finally able to get some real data and do a nice comparison. This was done on a part made from two thin plates bonded together one of aluminum and one of titanium. The images shown are just looking at one side of the bond, either the aluminum or titanium. The bottom row is real data sampled with a 3D Laser Doppler Vibrometer (LDV) the next row is a COMSOL model of the sample part with just the outer edges of the two parts bonded together. The next row is a full bond of the two parts, the SfePy row is removing the first 6 modes and the last is including all modes. All the images placement on the figure are based on their associated frequencies. 

For some reason when I use two materials I remove the first six modes to get rid of the first 6 free body modes, but it seems like I get another 6 because there are two materials. On the row SfePy rmv 6 we removed the second set of 6 free body modes and kept the frequencies associated in the same place and just shifted all the mode shapes down to match. It seems like this is the correct method to use to get the images and frequencies to all align. 

Based on the COMSOL model it seems we are not getting a complete bond between the two materials and therefore we are getting extra modes that are associated with this type of bonding. I used the convert mesh script to convert the mesh for this simulation as suggested. I am wondering if this just connects the outer edges of the meshes and not the entire faces. 

Please let me know if you need anymore information, I hope this is helpful. I was not able to include the mesh I used for this simulation since it is on another computer, but if you would like that too let me know.

![image](https://user-images.githubusercontent.com/49913632/145455954-05707631-5f7a-4766-9c1f-d746e7639b31.png)
![Mode Comparison](https://user-images.githubusercontent.com/49913632/145456024-a335c3e6-401c-4926-b3ce-973ef9a7244c.png)

**Comment by rc** [comment]
Great comparison! It does seem that the two material parts of the mesh are not connected. You can try some of the  advice given [here](https://sfepy.org/doc-devel/faq.html#mesh-related-tasks), or attach the mesh here, if possible. How was it constructed?

**Comment by lbeardslee1963** [comment]
In order to generate the mesh I followed the link you provided to convert two regions of a gmsh file into a joined mesh using the convert_mesh.py -m command. Here is the two meshes I used, the twoPlates mesh is before I ran the convert_mesh script, and the converted mesh is after running the script and the file used for the above sfepy images. 

Let me know if there is any other data I can provide.
[Plates.zip](https://github.com/sfepy/sfepy/files/7704903/Plates.zip)

**Comment by rc** [comment]
With the `twoPlates_converted.mesh`, I get the following eigenshapes:
![modes](https://user-images.githubusercontent.com/44282/146770618-63e4bc53-1180-414d-b3eb-d75a964b4137.png)
and the frequencies:
```
Mode 7 | Frequency 5,775.12 Hz
Mode 8 | Frequency 9,597.98 Hz
Mode 9 | Frequency 14,383.73 Hz
Mode 10 | Frequency 18,110.6 Hz
Mode 11 | Frequency 19,296.45 Hz
Mode 12 | Frequency 19,563.81 Hz
Mode 13 | Frequency 24,251.51 Hz
Mode 14 | Frequency 25,993.56 Hz
Mode 15 | Frequency 29,561.66 Hz
Mode 16 | Frequency 32,270.2 Hz
```
so I do not see the additional rigid body modes(?)

**Comment by rc** [comment]
FYI: I used the following command for the visualization:
```
python3 resview.py eigenshapes???.vtk -f u:f100%:wu --2d -e
```

**Comment by lbeardslee** [comment]
This is interesting, there seems to be a little mode switching between your and mine. I am still using the same code as above, if you run that do you get the same mode shapes?

I would be nice to get rid of the extra free body modes if possible, but my bigger concern is that the mesh seems to be detached in the middle. Based on the COMSOL comparison it seems that the mesh is only attached at the outer edges and that's why we are seeing the center modes, which don't show up in the real data either. Is there a way to fix this?

**Comment by rc** [comment]
The above results were obtained with your script. You are right, the mesh is disconnected in the middle - it can be seen if you cut the displaced mesh in e.g. paraview:
![shapes 0015](https://user-images.githubusercontent.com/44282/146841262-7616efa7-1372-40f0-9c22-a33fe684ad4a.png)



 I have generated a new mesh that you can try.

[mesh.zip](https://github.com/sfepy/sfepy/files/7748255/mesh.zip)

**Comment by lbeardslee** [comment]
I think that new mesh most likely solved the problems. I will send you a final comparison once its together showing COMSOL, real data, and the sfepy modes. Now the question is how did you fix the mesh to define the boundary? Is this something that can be done in paraview?

**Comment by rc** [comment]
I have generated a new mesh with the attached script (a helper for defining straight axis-aligned channels in a rectangular domain) as follows:
```
python3 gen_channels.py -d 5.8590000e-02,1.9480000e-02,4.0900000e-03 -c 2.9295000e-02,9.7400000e-03,2.0450000e-03 -s 20,10,5 -m both block_2m.vtk "xz=[(0,1,0,0.4)]"
```
[gen_channels.zip](https://github.com/sfepy/sfepy/files/7756916/gen_channels.zip)

How did you create the mesh in the first place?

**Comment by lbeardslee1963** [comment]
Here is the final comparison with the corrected mesh that you sent me, this shows a really great match. To create the mesh in the first place I defined two meshes in gmsh and then used the sfepy convert script to convert the mesh to a shared surface mesh. I need to find a way to define very complex meshes with multi domains, I think there might be a couple packages out there that will let me do this but I will need to do some looking and see how hard it will be to use them with sfepy. Do you have any suggestions?

![2mat_FEM_comparison_3-84 5](https://user-images.githubusercontent.com/63937434/147955458-0c6bc052-1e41-49be-8b22-3037c2b42f1e.png)

**Comment by rc** [comment]
Very nice match!

In [this document](http://sfepy.org/doc-devel/preprocessing.html) @vlukes shows how to prepare meshes for multi-material/domain objects so that the mesh is well connected. Note that sfepy can use almost any mesh format supported by [meshio](https://github.com/nschloe/meshio).

**Comment by rc** [comment]
Closing answered questions with no further reaction...
