### ISSUE TITLE
Create simulation logging with computation info?

### ISSUE THREAD

**Issue by lucascbarbosa** [sfepy/sfepy#763]
I'd like to know if it is possible to create a log message with all computational info like number of DOFs, memory used, etc. The number of cells of the geometry and the elapsed time I can get with `show_mesh_info.py`  and the time package.

**Comment by rc** [comment]
I assume you ask about the case when using `simple.py`, because when using the imperative API you can print all the information yourself. Then `simple.py` already prints many information as it runs, so what I do is I redirect the output to a file and then just extract the required info from that file. I am mostly doing it when using [soops](https://github.com/rc/soops) to run large parametric studies - it contains utilities for the output scraping, see e.g. the `scrape_output()` function [here](https://github.com/rc/time_tensors/blob/master/time_tensors.py). Or just use `awk/sed/grep` :) 

You can use
```
from sfepy.base.base import output
output.set_output(filename='log.txt', combined=True)
```
to have both the screen and file output, when using the `output()` function (does not work with `print()`.

Concerning the memory used, sfepy does not have this information - it is tricky due to C/fortran code use in all the packages that sfepy employs - those allocations are not seen by Python. I have used [memory_proflier](https://github.com/pythonprofilers/memory_profiler) in the time-based memory usage mode successfully.

**Comment by lucascbarbosa** [comment]
Sorry for the late response, had to work on some other stuff. If I understood you correctly, the pipeline is: I use `set_output()` to send all log to a txt file, and then use `scrape_output()` to extract the disred parameters? My question now is: if I want to get some parameter that is not informed in this log file, can I sort of create an API to compute that information?

**Comment by lucascbarbosa** [comment]
Another question: how I disable printing the log on the screen?

**Comment by rc** [comment]
Basically yes.

Or you might use e.g. a [postprocess_hook function](http://sfepy.org/doc-devel/users_guide.html?highlight=post_process_hook#solution-postprocessing), and print/save any additional information there, as this function gets the Problem instance. To get the total DOF counts:
```
variables = pb.get_variables()
print(variables.di)
```
See also [other hooks](http://sfepy.org/doc-devel/users_guide.html?highlight=hook#miscellaneous).

Or you could use the imperative API and print/save anything as desired.

**Comment by rc** [comment]
Closing answered questions with no further reaction...
